<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Configurations>Debug;Release</Configurations>
        <LangVersion>13</LangVersion>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <WarningsAsErrors />
        <NoWarn>1701;1702;NU1701;NU1900</NoWarn>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Realm" Version="10.18.0" />
    </ItemGroup>
</Project>